name: Nextgen XGBoost CI

on: [push, pull_request]

permissions:
  contents: read  # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-gpu:
    name: Test GPU
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=linux-amd64-gpu
    steps:
      # Restart Docker daemon so that it recognized the ephemeral disks
      - run: sudo systemctl restart docker
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Unstash testxgboost
        run: |
          aws s3 cp \
            s3://${{ env.RUNS_ON_S3_BUCKET_CACHE }}/cache/${{ github.repository }}/stash/11513939027/testxgboost \
             ./testxgboost
          chmod +x testxgboost
      - name: Fetch container from cache
        run: bash ops/docker_build.sh
        env:
          CONTAINER_ID: xgb-ci.gpu
          BRANCH_NAME: ${{ github.event.pull_request.number || github.ref_name }}
          USE_DOCKER_CACHE: 1
      - name: Run gtest
        run: |
          nvidia-smi
          python3 ops/docker_run.py \
            --container-id xgb-ci.gpu \
            --use-gpus \
            --run-args='--privileged' \
            -- ./testxgboost
          python3 ops/docker_run.py \
            --container-id xgb-ci.gpu \
            --use-gpus \
            --run-args='--cap-add=ALL' \
            -- ./testxgboost
